---
title: "Resources"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 4
    theme: paper
---

### Access the compiled contents of this course 

SAEON GSN has kindly compiled this course into a neat educational resource on their webpage. Find the site [here](https://rise.articulate.com/share/NwjZOmKC3Qo0ROu4wtDIsArONNdjLyK_#/).

### Access all lecture slides

* [Slides](https://drive.google.com/drive/folders/1CKLUeDWe-tRv-bdytUpZsNxE1C66yLzr?usp=sharing)

### Access the R project with scripts

* [Repository](https://github.com/jdmwhite/Intro_to_Spatial_Scripts)

### Access the video recordings

* [Intro & making a map](https://www.youtube.com/watch?v=sZS9tmHHXgM) 
* [Land cover change](https://www.youtube.com/watch?v=sjmbUQJuqRs) 
* [NDVI time series](https://www.youtube.com/watch?v=b0XYdyxp1zw) 
* [Species distribution models](https://www.youtube.com/watch?v=XnecxgSkiMg)

### Where to ask questions?
* The best place to find answers to your R problems is the internet. However, finding the most appropriate answer quickly is also a skill and will improve as your understanding of R grows. 
* So start with Google. Craft your questions to only have a few key words that may help refine your search. For example: "how to plot a raster" or "how to plot a raster R terra" if you want something `terra` related.
* Many of your Google queries may take you to [Stackoverflow](https://stackoverflow.com). This is a community full of R users who are asking and answering all things R related. There is a very good change that your query has already been answered here.

### Additional R resources

#### Getting started

  + [Download R](https://cran.r-project.org/)
  + [Download R Studio](https://www.rstudio.com/products/rstudio/download/#download)
  + [R Projects](https://www.tidyverse.org/blog/2017/12/workflow-vs-script)
  + [Folder structures](https://intro2r.com/dir-struct.html)
  + [File naming](https://intro2r.com/file-names.html)
  + [Script comments](https://bookdown.org/ndphillips/YaRrr/a-brief-style-guide-commenting-and-spacing.html)

#### Making a map

  + [dplyr cheatsheet - includes all other cheat sheets](https://www.rstudio.com/resources/cheatsheets/)
  + [more resources - blog to check out](https://towardsdatascience.com/7-data-wrangling-r-functions-for-your-next-data-science-project-in-under-5-minutes-d5a4ad55f99b)
  + [ggplot2 cheatsheet](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf) 
  + [sf cheatsheet](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjeqYu_q4P5AhXNPOwKHRnwCH0QFnoECAkQAQ&url=https%3A%2F%2Fosf.io%2Fan6b5%2Fdownload&usg=AOvVaw09ewjLkH09woLaWECSkpJC)
  + [importing data into R](https://intro2r.com/importing-data.html)
  + [Making maps in R - Geocomputation in R](https://geocompr.robinlovelace.net/adv-map.html)
  + [R-Spatial: Drawing beautiful maps](https://r-spatial.org/r/2018/10/25/ggplot2-sf.html)
  
#### Land cover change

  + [All of the functions in terra](https://rdrr.io/github/rspatial/terra/man/terra-package.html)
  + [OpenLand package: an alternative approach to what we explore](https://cran.r-project.org/web/packages/OpenLand/vignettes/openland_vignette.html)

#### NDVI time series

  + [MODISTools package](https://jepsonnomad.github.io/tutorials/MODISTools_Intro.html)
  + [MODISTools methods paper](https://onlinelibrary.wiley.com/doi/10.1002/ece3.1273)
  + [luna package (an alternative to MODISTools)](https://rspatial.org/terra/modis/2-download.html)
  + [rgee package (access way more remote sensing data through Google Earth Engine)](https://github.com/r-spatial/rgee)
  
#### Species distribution models

  + [Basic Intro to SDMs in R - rspatial](https://rspatial.org/terra/sdm/index.html)
  + [blockCV package](https://github.com/rvalavi/blockCV)
  + [blockCV methods paper](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13107)
  + [flexsdm package](https://sjevelazco.github.io/flexsdm/index.html)
  + [SDMtune package](https://consbiol-unibern.github.io/SDMtune/index.html)

#### Understanding R errors/warnings

Debugging your code is a crucial aspect of writing and editing any code/script based documents. 

Take a look this page on [Common R Mistakes](https://nickch-k.github.io/DataCommSlides/Lecture_04_Common_R_Problems.html) for help to debug your code.